version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: ms_sql_server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD
    ports:
      - 1433:1433

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - 5432:5432

  oracle_11g:
    image: oracleinanutshell/oracle-xe-11g:latest
    container_name: oracle_11g
    restart: always
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - 1521:1521

volumes:
  postgres_data:
    driver: local