version: '3.9'

services:
  gitea_server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
      - GITEA__database__DB_TYPE
      - GITEA__database__HOST
      - GITEA__database__NAME
      - GITEA__database__USER
      - GITEA__database__PASSWD
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8585:3000
      - 222:22
    depends_on:
      - db

  gitea_db:
    image: postgres:14
    container_name: gitea_db
    restart: always
    environment:
      - POSTGRES_USER=${GITEA_POSTGRES_USER}
      - POSTGRES_PASSWORD=${GITEA_POSTGRES_PASSWORD}
      - POSTGRES_DB=${GITEA_POSTGRES_DB}
    volumes:
      - gitea_postgres:/var/lib/postgresql/data

volumes:
  gitea:
    driver: local
  gitea_postgres:
    driver: local
