version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:jdk11
    container_name: jenkins
    restart: always
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "5050:8080"
      - "50000:50000"

  jekins_node:
    image: jenkins/jnlp-slave
    container_name: jenkins_node
    environment:
      - JENKINS_URL
      - JENKINS_SECRET
      - JENKINS_AGENT_NAME
      - JENKINS_AGENT_WORKDIR
    restart: always

volumes:
  jenkins:
    driver: local
