version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: ms_sql_server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD
    volumes:
      ms_sql_data:/var/opt/mssql
    ports:
      - 1433:1433

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgres/data
    ports:
      - 5432:5432

  oracle_19c:
    iamge: banglamon/oracle193db:19.3.0-ee
    container_name: oracle_19c
    restart: always
    environment:
      - ORACLE_SID
      - ORACLE_PDB
      - ORACLE_PWD
    volumes:
      - oracle19c_data:/opt/oracle/oradata
    ports:
      1521:1521

volumes:
  ms_sql_data:
    driver: local
  postgres_data:
    driver: local
  oracle19c_data:
    driver: local
